wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.7.6
    start_time: 1660677635.500223
    t:
      1:
      - 1
      - 9
      - 55
      2:
      - 1
      - 9
      - 55
      3:
      - 1
      - 7
      - 13
      - 23
      4: 3.7.6
      5: 0.13.1
      8:
      - 1
      - 5
